name: Deploy to Server

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy and build on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /root/apps
          echo "Pulling latest code..."
          git pull origin main
          echo "Installing dependencies..."
          yarn install --immutable
          echo "Building application..."
          yarn polkadot-dev-clean-build
          npx webpack --config packages/apps/webpack.config.cjs
          echo "Restarting application on port 2311..."
          pm2 restart nbc-apps || pm2 start "npx serve packages/apps/build -l 2311 -s" --name nbc-apps
          echo "Updating Nginx configuration..."
          sed -i 's/localhost:3000/localhost:2311/g' /etc/nginx/sites-available/nbc-apps
          systemctl reload nginx
          echo "Deployment completed successfully!"
          echo "Checking build files..."
          ls -la packages/apps/build/ 